"""initial schema

Revision ID: 2756ef184084
Revises: 
Create Date: 2026-02-11 01:54:14.994268

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2756ef184084'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingestion_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('last_tx_id', sa.String(), nullable=True),
    sa.Column('last_processed_at', sa.DateTime(), nullable=False),
    sa.Column('total_inserted', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingestion_state_name'), 'ingestion_state', ['name'], unique=True)
    op.create_table('scoring_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tx_source', sa.String(), nullable=False),
    sa.Column('config_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scoring_runs_id'), 'scoring_runs', ['id'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tx_id', sa.String(), nullable=True),
    sa.Column('sender', sa.String(), nullable=True),
    sa.Column('receiver', sa.String(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_id'), 'transactions', ['id'], unique=False)
    op.create_index(op.f('ix_transactions_receiver'), 'transactions', ['receiver'], unique=False)
    op.create_index(op.f('ix_transactions_sender'), 'transactions', ['sender'], unique=False)
    op.create_index(op.f('ix_transactions_tx_id'), 'transactions', ['tx_id'], unique=True)
    op.create_table('risk_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('wallet', sa.String(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('exposures_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('in_degree', sa.Integer(), nullable=False),
    sa.Column('out_degree', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['scoring_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_scores_id'), 'risk_scores', ['id'], unique=False)
    op.create_index(op.f('ix_risk_scores_run_id'), 'risk_scores', ['run_id'], unique=False)
    op.create_index(op.f('ix_risk_scores_wallet'), 'risk_scores', ['wallet'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_risk_scores_wallet'), table_name='risk_scores')
    op.drop_index(op.f('ix_risk_scores_run_id'), table_name='risk_scores')
    op.drop_index(op.f('ix_risk_scores_id'), table_name='risk_scores')
    op.drop_table('risk_scores')
    op.drop_index(op.f('ix_transactions_tx_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_sender'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_receiver'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_scoring_runs_id'), table_name='scoring_runs')
    op.drop_table('scoring_runs')
    op.drop_index(op.f('ix_ingestion_state_name'), table_name='ingestion_state')
    op.drop_table('ingestion_state')
    # ### end Alembic commands ###
